# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.14.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea
from gitea.models.username_tokens_body import UsernameTokensBody  # noqa: E501
from gitea.rest import ApiException


class TestUsernameTokensBody(unittest.TestCase):
    """UsernameTokensBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsernameTokensBody(self):
        """Test UsernameTokensBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea.models.username_tokens_body.UsernameTokensBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
