# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.14.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea
from gitea.models.payload_commit_verification import PayloadCommitVerification  # noqa: E501
from gitea.rest import ApiException


class TestPayloadCommitVerification(unittest.TestCase):
    """PayloadCommitVerification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayloadCommitVerification(self):
        """Test PayloadCommitVerification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea.models.payload_commit_verification.PayloadCommitVerification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
