# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.14.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea
from gitea.models.edit_attachment_options import EditAttachmentOptions  # noqa: E501
from gitea.rest import ApiException


class TestEditAttachmentOptions(unittest.TestCase):
    """EditAttachmentOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditAttachmentOptions(self):
        """Test EditAttachmentOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea.models.edit_attachment_options.EditAttachmentOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
