# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.14.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea
from gitea.models.commit_status import CommitStatus  # noqa: E501
from gitea.rest import ApiException


class TestCommitStatus(unittest.TestCase):
    """CommitStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommitStatus(self):
        """Test CommitStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea.models.commit_status.CommitStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
