# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.14.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea
from gitea.models.submit_pull_review_options import SubmitPullReviewOptions  # noqa: E501
from gitea.rest import ApiException


class TestSubmitPullReviewOptions(unittest.TestCase):
    """SubmitPullReviewOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubmitPullReviewOptions(self):
        """Test SubmitPullReviewOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea.models.submit_pull_review_options.SubmitPullReviewOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
