# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.14.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gitea
from gitea.models.file_delete_response import FileDeleteResponse  # noqa: E501
from gitea.rest import ApiException


class TestFileDeleteResponse(unittest.TestCase):
    """FileDeleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileDeleteResponse(self):
        """Test FileDeleteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gitea.models.file_delete_response.FileDeleteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
