apiVersion: v1
kind: Service
metadata:
  labels:
    app: yc
  name: yc
  namespace: testing
spec:
  ports:
  - nodePort: 30003
    port: 50001
    protocol: TCP
    targetPort: 50001
  selector:
    app: yc
  type: NodePort