---
apiVersion: v1
kind: Service
metadata:
  name: hello-minikube
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-minikube
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 31001
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: codebox-api
  namespace: testing
spec:
  type: NodePort
  selector:
    app: codebox-api
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 31001
      name: http


---
apiVersion: v1
kind: Service
metadata:
  name: codebox-api
  namespace: production
spec:
  type: NodePort
  selector:
    app: codebox-api
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 31002
      name: http