# Generated by Django 4.0.3 on 2023-01-21 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=256)),
                ('build_template', models.TextField()),
                ('deploy_template', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'unique_together': {('name', 'is_deleted')},
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('stage_type', models.IntegerField(choices=[(0, 'BUILD'), (1, 'DEPLOY')])),
                ('name', models.CharField(max_length=64)),
                ('seq', models.IntegerField()),
                ('namespace', models.CharField(default='default', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('limits_cpu', models.CharField(max_length=64)),
                ('limits_memory', models.CharField(max_length=64)),
                ('requests_cpu', models.CharField(max_length=64, null=True)),
                ('requests_memory', models.CharField(max_length=64, null=True)),
                ('replicas', models.IntegerField(default=1)),
                ('backoff_limit', models.IntegerField(default=3)),
                ('active_deadline_seconds', models.IntegerField(default=3600)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='k8s.project')),
                ('stage', models.ForeignKey(db_column='stage_id', on_delete=django.db.models.deletion.CASCADE, to='k8s.stage')),
            ],
            options={
                'unique_together': {('project_id', 'stage_id')},
            },
        ),
        migrations.CreateModel(
            name='ProjectEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=64)),
                ('value', models.TextField()),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='k8s.project')),
                ('stage', models.ForeignKey(db_column='stage_id', on_delete=django.db.models.deletion.CASCADE, to='k8s.stage')),
            ],
            options={
                'unique_together': {('project_id', 'stage_id', 'name')},
            },
        ),
    ]
