# Generated by Django 4.0.3 on 2023-01-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0002_projectenv_created_by_projectenv_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenv',
            name='is_deleted',
            field=models.BooleanField(default=0, verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='projectenv',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='is_deleted',
            field=models.BooleanField(default=0, verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AddField(
            model_name='stage',
            name='is_deleted',
            field=models.BooleanField(default=0, verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='stage',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
    ]
