# Generated by Django 4.0.3 on 2023-01-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0003_projectenv_is_deleted_projectenv_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='build_template',
            field=models.TextField(blank=True),
        ),
    ]
