# Generated by Django 4.0.3 on 2023-01-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0004_alter_project_build_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='containerPort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
