# Generated by Django 4.0.3 on 2023-01-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0005_projectresource_containerport'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='envs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
