# Generated by Django 4.0.3 on 2023-01-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0007_remove_projectresource_envs_projectenv_envs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=256),
        ),
    ]
