# Generated by Django 4.0.3 on 2023-01-23 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('k8s', '0008_alter_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('version', models.CharField(max_length=128)),
                ('state', models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'COMPLETED'), (3, 'FAILED'), (4, 'CLOSED'), (5, 'UNKONW')], default=0)),
                ('render_template', models.TextField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('current', models.ForeignKey(db_column='current_id', on_delete=django.db.models.deletion.PROTECT, to='k8s.stage')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除者')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.PROTECT, to='k8s.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'unique_together': {('project_id', 'version')},
            },
        ),
    ]
