# Generated by Django 4.0.3 on 2023-01-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0009_releasetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasetask',
            name='observed_generation',
            field=models.BigIntegerField(null=True),
        ),
    ]
