# Generated by Django 4.0.3 on 2023-01-24 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('k8s', '0010_releasetask_observed_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('state', models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'COMPLETED'), (3, 'FAILED'), (4, 'CLOSED'), (5, 'UNKONW')], default=0)),
                ('render_template', models.TextField(null=True)),
                ('observed_generation', models.BigIntegerField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除者')),
                ('stage', models.ForeignKey(db_column='stage_id', on_delete=django.db.models.deletion.PROTECT, to='k8s.stage')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.PROTECT, to='k8s.releasetask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
