# Generated by Django 4.0.3 on 2023-01-25 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0012_pipeline_project_pipeline_stage_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pipeline',
            field=models.ForeignKey(db_column='pipeline_id', on_delete=django.db.models.deletion.PROTECT, to='k8s.pipeline'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='pipeline',
            field=models.ForeignKey(db_column='pipeline_id', on_delete=django.db.models.deletion.PROTECT, to='k8s.pipeline'),
        ),
    ]
