# Generated by Django 4.0.3 on 2023-01-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0013_alter_project_pipeline_alter_stage_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='context',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='kubeconfig_content',
            field=models.TextField(null=True),
        ),
    ]
