# Generated by Django 4.0.3 on 2023-01-26 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k8s', '0015_releasetaskprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limits_cpu', models.CharField(max_length=64)),
                ('limits_memory', models.CharField(max_length=64)),
                ('requests_cpu', models.CharField(max_length=64, null=True)),
                ('requests_memory', models.CharField(max_length=64, null=True)),
                ('replicas', models.IntegerField(default=1)),
                ('backoff_limit', models.IntegerField(default=3)),
                ('active_deadline_seconds', models.IntegerField(default=3600)),
                ('stage', models.ForeignKey(db_column='stage_id', on_delete=django.db.models.deletion.PROTECT, to='k8s.releasetaskprogress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnvSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('stage', models.ForeignKey(db_column='stage_id', on_delete=django.db.models.deletion.PROTECT, to='k8s.releasetaskprogress')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
