# Generated by Django 4.0.3 on 2023-01-09 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iac.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('archive_url', models.URLField(verbose_name='playbook目录')),
                ('major', models.IntegerField(verbose_name='主版本')),
                ('minor', models.IntegerField(verbose_name='次版本')),
                ('micro', models.IntegerField(verbose_name='小版本')),
                ('commit', models.CharField(default='', max_length=40, verbose_name='提交id')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除者')),
            ],
            options={
                'db_table': 'release',
                'ordering': ['-major', '-minor', '-micro'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('playbook', models.CharField(default='main.yaml', max_length=50, verbose_name='playbook目录')),
                ('role', models.CharField(default='', max_length=50, null=True, verbose_name='role')),
                ('inventories', models.TextField(blank=True, null=True, verbose_name='主机清单')),
                ('envvars', models.TextField(default='', null=True, verbose_name='环境变量')),
                ('extravars', models.TextField(default='', null=True, verbose_name='额外变量')),
                ('forks', models.IntegerField(default=1, verbose_name='线程数')),
                ('timeout', models.IntegerField(default=3600, verbose_name='超时时间(秒)')),
                ('state', models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'COMPLETED'), (3, 'FAILED'), (4, 'CANCELED'), (5, 'TIMEOUT'), (6, 'UNKNOW')], default=0)),
                ('output', models.TextField(default='', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除者')),
                ('release', models.ForeignKey(db_column='release_id', on_delete=django.db.models.deletion.RESTRICT, to='iac.release')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('playbook', models.CharField(default='main.yaml', max_length=50, verbose_name='playbook目录')),
                ('role', models.CharField(default='', max_length=50, null=True, verbose_name='role')),
                ('inventories', models.TextField(blank=True, null=True, verbose_name='主机清单')),
                ('envvars', models.TextField(default='', null=True, verbose_name='环境变量')),
                ('extravars', models.TextField(default='', null=True, verbose_name='额外变量')),
                ('forks', models.IntegerField(default=1, verbose_name='线程数')),
                ('timeout', models.IntegerField(default=3600, verbose_name='超时时间(秒)')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='模板名称')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除者')),
                ('release', models.ForeignKey(db_column='release_id', on_delete=django.db.models.deletion.RESTRICT, to='iac.release')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'db_table': 'template',
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('state', models.IntegerField(choices=[(0, 'ok'), (1, 'failed'), (2, 'skipped'), (3, 'unreachable')])),
                ('play', models.CharField(max_length=512)),
                ('mission', models.CharField(max_length=512)),
                ('host', models.CharField(max_length=512)),
                ('ip', models.CharField(max_length=512)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('changed', models.BooleanField()),
                ('detail', models.JSONField()),
                ('play_pattern', models.CharField(max_length=128)),
                ('counter', models.IntegerField()),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='iac.task')),
            ],
            options={
                'db_table': 'taskevent',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('owner', models.CharField(max_length=50, verbose_name='仓库属主')),
                ('name', models.CharField(max_length=50, verbose_name='仓库名称')),
                ('url', models.URLField(verbose_name='gitea url')),
                ('token', models.CharField(default='', max_length=40, verbose_name='gitea token')),
                ('provider_class', models.CharField(default='iac.repositories.GiteaRepositoryProvider', max_length=128, validators=[iac.models.clean_provider_class], verbose_name='指定git仓库使用对应的provider来获取仓库信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'db_table': 'repository',
                'unique_together': {('owner', 'name', 'is_deleted')},
            },
        ),
        migrations.AddField(
            model_name='release',
            name='repository',
            field=models.ForeignKey(db_column='repository_id', on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='iac.repository', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='release',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改者'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('repository_id', 'major', 'minor', 'micro')},
        ),
    ]
