# Generated by Django 4.0.3 on 2023-01-10 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('iac', '0002_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('playbook', models.CharField(default='main.yaml', max_length=50, verbose_name='playbook目录')),
                ('role', models.CharField(default='', max_length=50, null=True, verbose_name='role')),
                ('inventories', models.TextField(blank=True, null=True, verbose_name='主机清单')),
                ('envvars', models.TextField(default='', null=True, verbose_name='环境变量')),
                ('extravars', models.TextField(default='', null=True, verbose_name='额外变量')),
                ('forks', models.IntegerField(default=1, verbose_name='线程数')),
                ('timeout', models.IntegerField(default=3600, verbose_name='超时时间(秒)')),
                ('name', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('beat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('crontab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='删除者')),
                ('interval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.intervalschedule')),
                ('release', models.ForeignKey(db_column='release_id', on_delete=django.db.models.deletion.RESTRICT, to='iac.release')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
            options={
                'db_table': 'periodtask',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='period',
            field=models.ForeignKey(db_column='period_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='iac.periodtask'),
        ),
    ]
