apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-flask
  name: simple-flask
  namespace: test
spec:
  ports:
  - nodePort: 30002
    port: 50001
    protocol: TCP
    targetPort: 50001
  selector:
    app: simple-flask
  type: NodePort